[build]
  command = "pnpm build"
  publish = "dist"

[functions]
  node_bundler = "esbuild"

[build.environment]
  NODE_VERSION = "22"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
